### ISSUE TITLE
Changes in loopback-next

### ISSUE THREAD

**Issue by janfa** [strongloop/loopback4-example-microservices#54]
In the latest [commit](https://github.com/strongloop/loopback-next/commit/bbf6be3e4a94332ef6ad86c4b7d48a51f957cd9a#diff-a8d0bb917b9fe74b2fe4f39fb38cb84f) of loopback-next the argument list of the loopback core class Server changed slightly, the Application instance has to be passed now.

**Comment by dhmlau** [comment]
@janfa , sorry about the late response.  There've been significant changes in the `Server` interface since Jun.  With this reason, I'd like to close this issue.  Feel free to open a separate issue if you encounter similar issue.  Thanks!
