### ISSUE TITLE
got issue

### ISSUE THREAD

**Issue by quyenbc** [strongloop/loopback4-example-microservices#63]
when i run: npm run build, i got this error message:
'bin' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! loopback-next-example@1.0.0 build: `bin/build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the loopback-next-example@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

**Comment by dhmlau** [comment]
@quyenbc , from the above message, it says node_modules is missing.  Did you run `npm install` after cloning this repo?

**Comment by corydeppen** [comment]
I think the [`cross-env`](https://www.npmjs.com/package/cross-env) package should be installed and used so that Windows users can run the Bash scripts. Once it's installed, just change the following:

```diff
- "build": "bin/build",
+ "build": "cross-env bin/build",

- "start": "bin/start",
+ "start": "cross-env bin/start",

- "stop": "bin/stop",
+ "stop": "cross-env bin/stop",
```

**Comment by thinusn** [comment]
Windows users can configure what shell npm should use for run scripts. In my case I used git bash as that supports execution of bash scripts. 

```bash
npm config set script-shell "C:\\Program Files\\git\\bin\\bash.exe"
```
See https://docs.npmjs.com/misc/config#script-shell

**Comment by dhmlau** [comment]
@quyenbc , is your problem resolved from @thinusn 's response?

**Comment by dhmlau** [comment]
Closing as resolved.
