### ISSUE TITLE
Add @thinusn as a maintainer

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback4-example-microservices#96]
Hello @thinusn! Based on your work on #78, we would like to invite to you to become a maintainer of this repository.

What would that mean for you:
 
 - Greater influence on the future direction of this example app
 - Commit (write) rights to this GitHub repository
 - Ability to review and land pull requests, edit/categorize/close issues
 - Access to a private Gitter room for LoopBack maintainers
 
If there is anything else that would make you a more successful maintainer, then let me know and I'll do my best to arrange it for you.
 
In return we ask you to follow the existing processes, see http://loopback.io/doc/en/contrib/Governance.html. This means mostly:
 - Be nice to others
 - Try to reach consensus with other maintainers before making a decision
 - Always use pull requests to make code changes
 - Honour our current conventions, see
   http://loopback.io/doc/en/contrib/triaging-pull-requests.html
   http://loopback.io/doc/en/contrib/style-guide.html
   (but feel free to propose changes to these conventions!)
 
To avoid possible confusion, we don't have any specific requirements about the amount of time you should spend on the project - just keep working on things that you find important to you, in a pace that suits you. We may ask you to take a look at issues and pull requests related to code you contributed yourself. This is primarily to make sure we don't accidentally break your stuff because of our lack of knowledge, and you can always excuse yourself :)
 
What do you think?

P.S. I hope you won't mind discussing this in public. I usually reach out via email, but you don't have any public email listed on GitHub nor in the git commit history.

cc @dhmlau @shimks @raymondfeng @virkt25 @b-admike

**Comment by dhmlau** [comment]
@bajtos , i know you've been trying to create a GH team with LB4 maintainers.  How is it coming along?

**Comment by bajtos** [comment]
Uh, I got sidetracked by other tasks, sorry for the delay! I'll put a note to make sure I make the necessary changes by the end of this week.

**Comment by bajtos** [comment]
@thinusn I sent you an invite to join our GitHub org. Once you accept, you will become a member of @strongloop/loopback-maintainers team, which will give you write permissions to all LB4 repositories.
